import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";

import Footer from "../components/Footer";
import Landing from "../components/Landing";
import Landing2 from "../components/Landing2";
import Landing3 from "../components/Landing3";
import Preview from "../components/Preview";
import Content from "../components/Content";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Starbucks Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fannn  nnm, mvicon.ico" />
      </Head>
      <main>
        <div className="space-y-5">
          <Landing3 />
          <Landing />
          <Landing2 />
        </div>

        <div className="py-9 bg-[#efefef] space-y-5">
          <Content
            contentImg="https://bit.ly/3MKqK33"
            contentH1="Starbucks® Rewards "
            contentP1="Summer season is here and so is our handcrafted Strawberry Acai Starbucks Refresha® Drink."
            contentP2="Order on the Starbucks® UK App for a speedy pick up. "
            contentButtons="Order now"
          />
          <Content
            contentImg="https://bit.ly/3xQyLPN"
            contentH1="Starbucks® Delivers"
            contentP1="You're one tap away from trying the Iced Brown Sugar Oat Shaken Espresso."
            contentP2="Get it delivered straight to your door with Starbucks® Delivers."
            contentButtons="Order now"
          />
        </div>
        <Preview />
      </main>
    </div>
  );
}
